version: "3.8"

services:
  app:
    build:
      context: .
    container_name: springboot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database-1.cd0ugyiem3rm.us-east-1.rds.amazonaws.com:3306/database-1
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    ports:
      - "8080:8080"
